"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import string, random, smtplib, psycopg2
from email.mime.text import MIMEText
from datetime import datetime
from django.conf import settings
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&*9wp6*j8auiv(*5$ncdygy(3#a)-o1c48da_933l6d2aer5^a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'appbackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


STATIC_URL = 'static/'
APPEND_SLASH = False
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOW_ALL_ORIGINS = True


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


def sendResponse(request, resultCode, data, action="no action"):
    """Стандарт response үүсгэх"""
    response = {}
    
    # resultCode-г зөв төрөлд хөрвүүлэх
    if isinstance(resultCode, (list, dict)):
        resultCode = 400
    elif not isinstance(resultCode, (int, str)):
        resultCode = 500
    
    # resultCode-г string болгон хөрвүүлэх
    code_str = str(resultCode)
    
    response["resultCode"] = resultCode
    response["resultMessage"] = resultMessages.get(code_str, f"Unknown status code: {resultCode}")
    response["data"] = data
    
    # data-н хэмжээг тооцоолох
    if isinstance(data, (list, dict, str)):
        response["size"] = len(data)
    else:
        response["size"] = 0
    
    response["action"] = action
    response["curdate"] = datetime.now().strftime('%Y/%m/%d %H:%M:%S')

    return response



# result Messages - БҮХ KEY-г STRING БОЛГОСОН
resultMessages = {
    "200": "Амжилттай",
    "400": "Bad Request",
    "404": "Хоосон байна",
    "500": "Серверийн алдаа",
    "505": "Баазын алдаа",
    "1000": "Бүртгэх боломжгүй. Майл хэдийн бүртгэлтэй байна",
    "1001": "Хэрэглэгч амжилттай бүртгэгдлээ. Баталгаажуулах майл илгээгдлээ. 24 цагийн дотор баталгаажуулна уу.",
    "1002": "Амжилттай нэвтэрлээ",
    "1003": "Амжилттай баталгаажлаа",
    "1004": "Хэрэглэгчийн нэр нууц үг буруу байна",
    "1005": "edituser success",
    "1006": "getuserresume success",
    "1007": "getalluser success",
    "3001": "ACTION BURUU",
    "3002": "METHOD BURUU",
    "3003": "JSON BURUU",
    "3004": "Token-ийн хугацаа дууссан. Идэвхгүй token байна.",
    "3005": "NO ACTION",
    "3006": "Login service key дутуу",
    "3007": "Register service key дутуу",
    "3008": "Баталгаажсан хэрэглэгч байна. Register service.",
    "3009": "token буруу эсвэл хугацаа дууссан",
    "3010": "Хэрэглэгчийн бүртгэл баталгаажлаа",
    "3011": "Forgot password verified",
    "3012": "Forgot password хүсэлт илгээлээ",
    "3013": "Forgot password хэрэглэгч олдсонгүй",
    "3014": "Баталгаажсан хэрэглэгч байна. Өмнөх бүртгэлээрээ нэвтэрнэ үү. Mail Link",
    "3015": "no token parameter",
    "3016": "forgot service key дутуу",
    "3017": "not forgot and register GET token",
    "3018": "reset password key дутуу",
    "3019": "мартсан нууц үгийг шинэчиллээ",
    "3020": "token буруу байна эсвэл хугацаа дууссан. Нууц үгийг шинэчилж чадсангүй",
    "3021": "change password service key дутуу",
    "3022": "нууц үг амжилттай солигдлоо",
    "3023": "хуучин нууц үг таарахгүй байна",
    "3024": "edituser service key дутуу",
    "3025": "getuserresume service key дутуу",
    "3026": "getalluser service key дутуу",
    "5001": "Login service дотоод алдаа",
    "5002": "Register service дотоод алдаа",
    "5003": "Forgot service дотоод алдаа",
    "5004": "GET method token дотоод алдаа",
    "5005": "reset password service дотоод алдаа",
    "5006": "change password service дотоод алдаа",
    "5007": "edituser service дотоод алдаа",
    "5008": "getuserresume service дотоод алдаа",
    "5009": "getalluser service дотоод алдаа",
}


def connectDB():
    """Өгөгдлийн сантай холбогдох"""
    conn = psycopg2.connect(
        dbname="GYM", 
        user="postgres", 
        password="1234", 
        host="localhost", 
        port="5432"
    )
    return conn


def disconnectDB(conn):
    """Өгөгдлийн сангаас салах"""
    if conn:
        conn.close()


def generateStr(length):
    """Санамсаргүй string үүсгэх"""
    characters = string.ascii_lowercase + string.digits
    password = ''.join(random.choice(characters) for i in range(length))
    return password


def sendMail(recipient, subj, bodyHtml):
    """Мэйл илгээх"""
    sender_email = "testmail@mandakh.edu.mn"
    sender_password = "Mandakh2"
    recipient_email = recipient
    subject = subj
    body = bodyHtml
    html_message = MIMEText(body, 'html')
    html_message['Subject'] = subject
    html_message['From'] = sender_email
    html_message['To'] = recipient_email
    with smtplib.SMTP('smtp-mail.outlook.com', 587) as server:
        server.ehlo()
        server.starttls()
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, recipient_email, html_message.as_string())
        server.quit()
        